version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - my_volume:/app
    depends_on:
      - db
    

  db:
    image: postgres
    environment:
      - POSTGRES_DB=djangoapp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass

volumes:
  my_volume:
